name: Build mempodroid

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download & Extract Android NDK r21e
        run: |
          wget -q https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
          unzip -q android-ndk-r21e-linux-x86_64.zip

      - name: Compile mempodroid
        run: |
          ./android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi16-clang \
          -O2 -Wall mempodroid.c -o mempodroid -static

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: mempodroid-binary
          path: mempodroid

      - name: Compile diaggetroot
        run: |
          ./android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/clang \
            -target armv7a-linux-androideabi14 \
            -O2 -Wall diaggetroot.c -o diaggetroot

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: diaggetroot-binary
          path: diaggetroot
